### ISSUE TITLE
Implement the new `categories` property for the field descriptor meta

### ISSUE THREAD

**Issue by djvanderlaan** [djvanderlaan/datapackage#5]
V2 of the spec defines a `categories` property: https://datapackage.org/standard/table-schema/#categories. The current implementation has similar functionality using the `codelist` property. This needs to be converted.

- [x] Modify `dpcodelist` to use the new field
- [x] Rename `dpcodelist` to `dpcategorieslist`: we will use `categories` to refer to the `categories` property and `categorieslist` to the actual data.frame with the values and labels of the categories. 
- [x] Modify `dpgeneratefielddescriptor` to generate the `categories` field. By default this is the `[{"value":1, "label": "apple"}]` variant. 
- [x] Modify the examples in the vignette
- [x] Change `dpgeneratefielddescriptor` and `dpgeneratedataresources` to also allow for the (not yet official) format where the categorieslist is stored in a data resource. 
- [ ] Change `dpgeneratefielddescriptor` and `dpgeneratedataresources` to also allow for the simplified format (`["apples"]`). 
- [x] Add examples to the vignettes using categories lists in resources
